### ISSUE TITLE
Require PRs to pass linters

### ISSUE THREAD

**Issue by groteworld** [doublespeakgames/adarkroom#188]
This would require two parts:
- [ ] Lint the current code
- [ ] Set up TravisCI

This comes from discussion in #187 and #176 since partial CSSLint linting would be considered.

**Comment by rgravina** [comment]
I've removed the ```.jshintrc``` (since we haven't decided on a linter) and created a pull request #204 which fixes the issues outlined in the previous comment. I think it might give you a head start on fixing the existing issues? Interested?

**Comment by anubisthejackle** [comment]
If we're going to do this properly, I think standardizing a linter is the first step. I have both JSHint and JSLint, so either works for me. Standardizing allows packaging of the config file for that linter, which let's us define what we want for the config, such as tabs not spaces, etc.

I'd say since so much work has been done with JSHint already, I'd put a +1 for JSHint.

**Comment by Continuities** [comment]
JSHint works for me. I've had some experience with it in the past.

@skj3gg is right about the syntax of the `Events.EventPool` code. Sorry for not commenting on that sooner. I'm totally fine with switching it to `[].concat` instead of `new Array().concat`. Were I writing it today, I'd probably use array literal notation.

**Comment by skj3gg** [comment]
Cool with me. I'll make this PR my mission today.

**Comment by rgravina** [comment]
>  I'll make this PR my mission today

Mission accomplished, thanks :+1: There's just a few errors left, mostly related to defining functions inside of a loop or using the same for loop instance variable in a second loop in a function. A bit of refactoring should fix them (but I didn't want to attempt that just yet).

I've been using this ```.jshintrc````, FYI (not committed in #204 as I wasn't sure what linter you were going to use at that time).
```
{
  "eqnull": true,
  "sub": true,
  "multistr": true
}
```

**Comment by chuglydude** [comment]
Should i help on this case?

**Comment by gitupofftheflooranddosomework** [comment]
This can be closed, everything is fixed in this

**Comment by esaruoho** [comment]
@groteworld @grotewold could you close this ticket, please? (in case everything has been fixeded)
