### ISSUE TITLE
Leaving on a journey doesn't work

### ISSUE THREAD

**Issue by drandrew666** [doublespeakgames/adarkroom#666]
I try and leave a place on a A Dusty Path and I can't leave the menu. Have to refresh. On safari

**Comment by Nicknameismynickname** [comment]
Same hear it’s annoying I got an iron sword from a cave but couldn’t leave :(

**Comment by Nicknameismynickname** [comment]
Here* 😂

**Comment by Continuities** [comment]
Hm... I'll look into it. Sorry folks!

**Comment by Continuities** [comment]
The new audio engine breaks in Safari in a way that I don't have time to debug right now, so I just disabled it =(
If you do a full refresh, everything should be working again.

**Comment by Nicknameismynickname** [comment]
To whom it may concern,
I usually play on my school IPad and now my district has me sign into a web
filter and your website is classified as a game.

                                               Sincerely,
                                               Nicholas Saldanha


26saldanhan@ttsdstudents.org

On Oct 5, 2020, at 9:38 AM, Michael Townsend <notifications@github.com>
wrote:

﻿

The new audio engine breaks in Safari in a way that I don't have time to
debug right now, so I just disabled it =(
If you do a full refresh, everything should be working again.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/doublespeakgames/adarkroom/issues/666#issuecomment-703748333>,
or unsubscribe

**Comment by Continuities** [comment]
This isn't exactly the right place to discuss this, but maybe they're not clever enough to block web proxies 😉
https://www.proxysite.com/

**Comment by Nicknameismynickname** [comment]
To Whom it may Concern,
Yeah they are.

                                               Sincerely,
                                               Nicholas Saldanha


26saldanhan@ttsdstudents.org

On Oct 5, 2020, at 2:25 PM, Michael Townsend <notifications@github.com>
wrote:

﻿

This isn't exactly the right place to discuss this, but maybe they're not
clever enough to block web proxies 😉
https://www.proxysite.com/

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/doublespeakgames/adarkroom/issues/666#issuecomment-703897611>,
or unsubscribe

**Comment by Continuities** [comment]
Drat. How about loading the game directly from Github?
https://rawcdn.githack.com/doublespeakgames/adarkroom/9e19425a9effb50cf7d9498994c7bbad34e7828a/index.html

**Comment by Nicknameismynickname** [comment]
To whom it may concern,
Yay it worked. I lost all my progress but at least I can play it now. THANK
YOU!!

                                               Sincerely,
                                               Nicholas Saldanha


26saldanhan@ttsdstudents.org

On Oct 5, 2020, at 2:54 PM, Michael Townsend <notifications@github.com>
wrote:

﻿

Drat. How about loading the game directly from Github?
https://rawcdn.githack.com/doublespeakgames/adarkroom/9e19425a9effb50cf7d9498994c7bbad34e7828a/index.html

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/doublespeakgames/adarkroom/issues/666#issuecomment-703910106>,
or unsubscribe
